zed_servo_controller:
  joints: {
    type: string_array,
    default_value: [],
    description: "Joints controlled by the zed servo controller",
    read_only: true,
    validation: {
      unique<>: null,
    }
  }
  zed_servo_joint: {
    type: string,
    default_value: "",
    description: "zed_servo_controller description here",
    read_only: true,
  }


  #validation: {
    #  not_empty<>: null
    #}